# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_tableurl_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableurl',
            name='shortlink',
            field=models.URLField(default=''),
        ),
    ]
