# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_tableurl_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableurl',
            name='id',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
    ]
