# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20160616_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableurl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
